server:
  port: 8080

spring:
  application:
    name: b2b-EcPlatform-API
  profiles:
    active: dev

token:
  expiration-minutes: 20

#nas:
#  expiration-days: 30
#  cron:
#    expression: "0 0 2 * * ?"

