server:
  port: 8080

spring:
  application:
    name: b2b-EcPlatform-API
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testschema
    username: root
    password: ooxx1998
#  jpa:
#    database-platform: org.hibernate.dialect.SQLServerDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect

ecws:
  domain: https://tb2b.518fb.com/ecws/json/service
  header:
    fromSys: "B2A"
    sysPwd: "lYKMhPW8SGg="
  get-verification-image:
    header:
      from-sys: "B2A"
      sys-pwd: "lYKMhPW8SGg="
      function-code: "FBECCOMSTA1032"
      account: "12546"
      user-ip: "192.168.50.138"
    fbeccomsta1032-rQ:
      system: "B2A"
      insure-type: "FBINSAPP"
      verification-types: "1"

  login:
    header:
      from-sys: "B2A"
      sys-pwd: "lYKMhPW8SGg="
      function-code: "FBECAPPCERT1001"
      account: "12546"
      user-ip: "192.168.50.138"
    fbecappcert1001-rQ:
      ip-address: "192.168.50.138"
      device: "iOS"
      code-name: "ASUS P01T_1"
      device-id: "589241cf66bb05f7"
      os-version: "6.0.1"
      app-version: "1.01.81"
      agent-id: ""
      login-id: ""
      sales-id: ""
      agent-name: ""
      union-num: ""
      admin-id: ""
      return-pfx: "1"
      identify: "1"
      emp-no: "12546"
      password: "1qaz2wsx"
      token: ""
      verification-code: ""
      client: ""
      sid: ""

  sso-token:
      header:
        from-sys: "B2A"
        sys-pwd: "lYKMhPW8SGg="
        function-code: "FBECCOMSTA1040"
      fbeccomsta1040-rQ:
        union-num: ""
        account: ""
        source: "FBInsAgent"
        des-type: ""
        des-module: ""
        des-function: "FBInsAgentAPP"
        type: ""
        parameter: ""

sso-login:
    test:
      webServiceAcc: zAq1xSw2
      webServicePwd: cDe3vFr4
    production:
      webServiceAcc: zaq12wsxcde34rfV
      webServicePwd: vfr43edcxsw21qaZ

policy-detail:
  domain: "http://localhost:8080"





