server:
  port: 8080

spring:
  application:
    name: b2b-EcPlatform-API
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TestSchema;encrypt=false;trustServerCertificate=true;
    username: sa
    password: Systex0624
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect




