server:
  port: 8080

spring:
  application:
    name: b2b-EcPlatform-API
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://210.63.39.105:6214;databaseName=NewString;encrypt=false;trustServerCertificate=true;
    username: sa
    password: Systex0624.
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect




