server:
  port: 8088

spring:
  application:
    name: b2b-EcPlatform-API
  profiles:
    active: dev

token:
  expiration-minutes: 20

scheduling:
  cron-expression: 0 0 2 * * ?
#  cron-expression: "*/5 * * * * *"
  expiration-days: 30
  clean-path: /path/to/nas


